chore: Update GitHub Actions workflow configuration

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -21,78 +21,78 @@ permissions:
   pull-requests: write
 
 jobs:
-  sonar_scan:
-    name: Sonar Scan
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GH_TOKEN }}
-          fetch-depth: 0
-
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: 1.22
-
-      - name: Run Tests with Coverage
-        run: |
-          go test ./... -coverprofile=coverage.out -covermode=atomic
-          go tool cover -func=coverage.out
-
-      - name: Convert coverage to SonarQube format
-        run: |
-          echo "mode: atomic" > coverage.out.tmp
-          tail -n +2 coverage.out >> coverage.out.tmp
-          mv coverage.out.tmp coverage.out
-
-      - name: Run GoSec
-        uses: securego/gosec@v2.21.4
-        continue-on-error: true
-        id: gosec
-        with:
-          args: -fmt=sonarqube -out=gosec.json ./...
-
-      - uses: sonarsource/sonarqube-scan-action@master
-        id: sonar_scan
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-        with:
-          args: >
-            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
-            -Dsonar.sources=.
-            -Dsonar.go.gopath=${{ env.GOPATH }}
-            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
-            -Dsonar.go.coverage.reportPaths=coverage.out
-            -Dsonar.externalIssuesReportPaths=gosec.json
-            -Dsonar.coverage.exclusions=**/*_test.go
-            -Dsonar.go.tests.reportPaths=coverage.out
-            -Dsonar.test.inclusions=**/*_test.go
-
-      - uses: sonarsource/sonarqube-quality-gate-action@master
-        id: sonar_quality_gate
-        timeout-minutes: 5
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-
-      - name: Run script
-        id: sonar_metrics
-        if: ${{ github.event_name == 'pull_request' && always()}}
-        env:
-          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
-          SONARQUBE_URL: ${{ secrets.SONAR_HOST_URL }}
-          SONARQUBE_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONARQUBE_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-          GITHUB_REPO_NAME: ${{ github.repository }}
-          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
-        run: |
-          python .config/scripts/generate_sonar_metrics_comment.py
-
-      - name: Fail CI if Scan or Quality Gate fails
-        if: ${{ steps.sonar_scan.outcome == 'failure' || steps.sonar_quality_gate.outcome == 'failure' }}
-        run: exit 1
+#  sonar_scan:
+#    name: Sonar Scan
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          token: ${{ secrets.GH_TOKEN }}
+#          fetch-depth: 0
+#
+#      - name: Set up Go
+#        uses: actions/setup-go@v5
+#        with:
+#          go-version: 1.22
+#
+#      - name: Run Tests with Coverage
+#        run: |
+#          go test ./... -coverprofile=coverage.out -covermode=atomic
+#          go tool cover -func=coverage.out
+#
+#      - name: Convert coverage to SonarQube format
+#        run: |
+#          echo "mode: atomic" > coverage.out.tmp
+#          tail -n +2 coverage.out >> coverage.out.tmp
+#          mv coverage.out.tmp coverage.out
+#
+#      - name: Run GoSec
+#        uses: securego/gosec@v2.21.4
+#        continue-on-error: true
+#        id: gosec
+#        with:
+#          args: -fmt=sonarqube -out=gosec.json ./...
+#
+#      - uses: sonarsource/sonarqube-scan-action@master
+#        id: sonar_scan
+#        env:
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+#        with:
+#          args: >
+#            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
+#            -Dsonar.sources=.
+#            -Dsonar.go.gopath=${{ env.GOPATH }}
+#            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
+#            -Dsonar.go.coverage.reportPaths=coverage.out
+#            -Dsonar.externalIssuesReportPaths=gosec.json
+#            -Dsonar.coverage.exclusions=**/*_test.go
+#            -Dsonar.go.tests.reportPaths=coverage.out
+#            -Dsonar.test.inclusions=**/*_test.go
+#
+#      - uses: sonarsource/sonarqube-quality-gate-action@master
+#        id: sonar_quality_gate
+#        timeout-minutes: 5
+#        env:
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#
+#      - name: Run script
+#        id: sonar_metrics
+#        if: ${{ github.event_name == 'pull_request' && always()}}
+#        env:
+#          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
+#          SONARQUBE_URL: ${{ secrets.SONAR_HOST_URL }}
+#          SONARQUBE_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#          SONARQUBE_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
+#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+#          GITHUB_REPO_NAME: ${{ github.repository }}
+#          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
+#        run: |
+#          python .config/scripts/generate_sonar_metrics_comment.py
+#
+#      - name: Fail CI if Scan or Quality Gate fails
+#        if: ${{ steps.sonar_scan.outcome == 'failure' || steps.sonar_quality_gate.outcome == 'failure' }}
+#        run: exit 1
 
   check_vulnerabilities:
     runs-on: ${{ matrix.os }}
